# Generated by Django 3.0.8 on 2020-07-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['age'], 'verbose_name': 'Возраст'},
        ),
    ]
