# Generated by Django 3.0.8 on 2020-07-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200707_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='no category', max_length=50, verbose_name='Категория'),
        ),
    ]
