# Generated by Django 3.0.8 on 2020-07-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Раздел для статей')),
                ('number', models.IntegerField(verbose_name='Номер раздела')),
                ('category', models.CharField(default='no category', max_length=50, verbose_name='Категория обучения')),
            ],
            options={
                'verbose_name': 'Раздел статьи',
                'verbose_name_plural': 'Разделы статей',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория обучения', 'verbose_name_plural': 'Категории обучения'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='number',
        ),
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.CharField(default='no section', max_length=50, verbose_name='Раздел статьи'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Категория обучения'),
        ),
    ]
